name: duggy
description: "Cricket club management app for players"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

dependencies:
  flutter:
      sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  badges: ^3.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
