name: duggy
description: "Cricket club management app for players"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

dependencies:
  flutter:
      sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  badges: ^3.1.2
  flutter_markdown: ^0.7.4+1
  file_picker: ^8.0.0+1

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/duggy_logo_192.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/duggy_logo_192.png"
    background_color: "#003f9b"
    theme_color: "#003f9b"
  windows:
    generate: true
    image_path: "assets/images/duggy_logo_192.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/duggy_logo_192.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
