name: duggy
description: "Cricket club management app for players"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ^3.8.1
  flutter: ">=3.35.1 <4.0.0"

dependencies:
  flutter:
      sdk: flutter
  http: ^1.1.0
  http_parser: ^4.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
  file_picker: ^10.3.2
  flutter_sound: ^9.7.1
  audioplayers: ^6.0.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  image_cropper: ^9.1.0
  share_plus: ^11.1.0
  package_info_plus: ^8.0.0

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  crypto: ^3.0.6
  flutter_contacts: ^1.1.7+1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/duggy_logo_192.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/duggy_logo_192.png"
    background_color: "#003f9b"
    theme_color: "#003f9b"
  windows:
    generate: true
    image_path: "assets/images/duggy_logo_192.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/duggy_logo_192.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/upi/
